name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: ${{ matrix.os }} / Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Install graphviz
        run: sudo apt install -y --no-install-recommends graphviz

      - name: Test
        run: |
          npm run mocha
          npm run debug
          npm run generate
